name: bun-diff-action
author: Anna Bocharova
description: A composite action that writes the diff of bun.lock file into a comment of pull request
branding:
  icon: list
  color: green
inputs:
  working-directory:
    description: Directory to find bun.lockb file
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Set up diff
      shell: bash
      run: bunx bunpare
    - name: Collect the diff
      id: collect
      shell: bash
      run: |
        echo 'comment<<EOF' >> $GITHUB_OUTPUT
        echo "<!-- bun-diff-action -->" >> $GITHUB_OUTPUT
        echo ${{ github.event.pull_request.head.sha }} >> $GITHUB_OUTPUT
        echo '```diff' >> $GITHUB_OUTPUT
        git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} bun.lockb >> $GITHUB_OUTPUT
        echo '```' >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: bun-diff-action
    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.collect.outputs.comment }}
        reactions: rocket
    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
        body: ${{ steps.collect.outputs.comment }}
        reactions: hooray
