name: Test
on: pull_request
permissions:
  pull-requests: write # for comments in PRs
jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: # required!
          fetch-depth: 0
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Show the bun lock diff
        uses: ./
        with:
          working-directory: test
